### ISSUE TITLE
Server error 500 when clicking Mesh API "Installs" from any other page

### ISSUE THREAD

**Issue by LydonThorpe** [WillNilges/meshdb#190] opened 2024-02-14 03:33 UTC
http://db.grandsvc.mesh/admin/meshapi/install/ (accessed via SN1 Wireguard VPN) gives server error 500.
When clicked from either the /admin/ root page or from another (ex /meshapi/building/)

**Comment by Andrew-Dickinson** [comment] 2024-02-14 06:31
Hm. I'm unable to reproduce it locally, @WillNilges maybe this is related to the force-push stuff tonight

**Comment by Andrew-Dickinson** [comment] 2024-02-14 06:33
The box is set to SSH key only auth, and I don't have access, so Willard will have to look at this tomorrow

**Comment by Andrew-Dickinson** [comment] 2024-02-15 23:32
Issue appears to be gone, closing for now

**Comment by Andrew-Dickinson** [comment] 2024-02-17 17:59
Hm this is back again this afternoon...

**Comment by Andrew-Dickinson** [comment] 2024-02-18 21:41
Root cause is likely out-of-date code on the import box. Running an off-cycle import with the latest code to check

**Comment by Andrew-Dickinson** [comment] 2024-02-19 04:05
Yep confirmed. Closing

**Closed by Andrew-Dickinson** 2024-02-19 04:05 UTC
Labels: bug, Admin Panel
